version: '1'
services:
  bot:
    runtime: python3.11
    build:
      requirements: requirements.txt
    run: "python bot.py"
    ports:
      - 8080
    env:
      - TELEGRAM_BOT_TOKEN
      - WEBHOOK_URL
      - WEBHOOK_SECRET
